# Generated by Django 4.1.1 on 2022-09-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_uploads_uploaded_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploads',
            name='uploaded_file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
