# Generated by Django 4.1.1 on 2022-10-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_uploads_uploaded_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploads',
            name='delete_code',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
    ]
